cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'curl'
brew 'flow'
brew 'freetype'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'macvim'
brew 'openssl'
brew 'readline'
brew 'postgresql'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'the_silver_searcher'
brew 'tldr'
brew 'unrar'
brew 'watchman'
brew 'wget'
brew 'yarn' --without-node
brew 'youtube-dl'
brew 'z'

# cask '1password'
# cask 'adium'
cask 'atom'
cask 'docker'
cask 'firefox'
cask 'google-chrome'
# cask 'handbrake'
cask 'sketch'
cask 'slack'
cask 'spotify'
# cask 'steam'
# cask 'transmission'
# cask 'tunnelbear'
cask 'vlc'
cask 'xquartz'
